import { z } from "zod";

const ConfigSchema = z.object({
  port: z.coerce.number().int().positive().default(3200),
  dbPath: z.string().min(1).default("./data/valor.db"),
  dbBackend: z.enum(["sqlite", "postgres"]).default("sqlite"),
  dbPostgresUrl: z.string().optional(),
  logLevel: z.enum(["debug", "info", "warn", "error"]).default("info"),
  anthropicApiKey: z.string().optional(),
  ollamaBaseUrl: z.string().optional(),
  ollamaStatusUrl: z.string().optional(),
  sigintUrl: z.string().url().default("http://localhost:8082"),
  defaultModel: z.string().default("ollama/gemma3:12b"),
  claudeDefaultModel: z.string().default("claude-sonnet-4-5"),
  analystModel: z.string().default("qwen3:latest"),
  codexCli: z.enum(["auto", "on", "off"]).default("auto"),
  codexCliPath: z.string().default("codex"),
  codexModels: z.string().default("codex,gpt-5.2-codex,gpt-5.2,gpt-5.1-codex-max").transform((s) => s.split(",").map((m) => m.trim()).filter(Boolean)),
  grokCli: z.enum(["auto", "on", "off"]).default("auto"),
  grokCliPath: z.string().default("grok"),
  grokModels: z.string().default("grok,grok-build,grok-composer-2.5-fast,grok-4,grok-code").transform((s) => s.split(",").map((m) => m.trim()).filter(Boolean)),
  directorModel: z.string().default("gemma3:27b"),
  directorGear2Model: z.string().default("nemotron-cascade-2:latest"),
  directorConfidenceThreshold: z.coerce.number().min(0).max(10).default(5),
  natsUrl: z.string().default("nats://localhost:4222"),
  disabledGates: z.string().default("").transform((s) => s.split(",").map((g) => g.trim()).filter(Boolean)),
  storeBackend: z.enum(["folder", "sqlite"]).default("folder"),
  agentsDir: z.string().default("./agents"),
  missionsDir: z.string().default("./missions"),
  adminUsername: z.string().min(1).default("director"),
  adminPassword: z.string().optional(),
});

export type Config = z.infer<typeof ConfigSchema>;

export const config: Config = ConfigSchema.parse({
  port: process.env.VALOR_PORT,
  dbPath: process.env.VALOR_DB_PATH,
  dbBackend: process.env.DB_BACKEND,
  dbPostgresUrl: process.env.DB_POSTGRES_URL,
  logLevel: process.env.LOG_LEVEL,
  anthropicApiKey: process.env.ANTHROPIC_API_KEY,
  ollamaBaseUrl: process.env.OLLAMA_BASE_URL,
  ollamaStatusUrl: process.env.OLLAMA_STATUS_URL,
  sigintUrl: process.env.SIGINT_URL,
  defaultModel: process.env.VALOR_DEFAULT_MODEL,
  claudeDefaultModel: process.env.CLAUDE_DEFAULT_MODEL,
  analystModel: process.env.ANALYST_MODEL,
  codexCli: process.env.CODEX_CLI,
  codexCliPath: process.env.CODEX_CLI_PATH,
  codexModels: process.env.CODEX_MODELS,
  grokCli: process.env.GROK_CLI,
  grokCliPath: process.env.GROK_CLI_PATH,
  grokModels: process.env.GROK_MODELS,
  directorModel: process.env.DIRECTOR_MODEL,
  directorGear2Model: process.env.DIRECTOR_GEAR2_MODEL,
  directorConfidenceThreshold: process.env.DIRECTOR_CONFIDENCE_THRESHOLD,
  natsUrl: process.env.NATS_URL,
  disabledGates: process.env.DISABLED_GATES,
  storeBackend: process.env.STORE_BACKEND,
  agentsDir: process.env.AGENTS_DIR,
  missionsDir: process.env.MISSIONS_DIR,
  adminUsername: process.env.VALOR_ADMIN_USER,
  adminPassword: process.env.VALOR_ADMIN_PASSWORD,
});
